---
language: python
python: "2.7"

env:
  - SCENARIO=debian
  - SCENARIO=ubuntu

sudo: required

dist: trusty

services:
  - docker

install:
  - pip install molecule docker

script:
  - molecule --base-config molecule/shared/base.yml test --scenario-name $SCENARIO
