---
- name: Converge
  hosts: all
  roles:
    - role: boutetnico.backup
      backup_extra_dir:
        - /home/backupd/storage
      backup_services:
        - name: files
          script: files.sh
          vars:
            files_path: /var/www/site/data
            tar_options: '--exclude ./path'
          cron:
            day: 1
            hour: 6
            minute: 0
        - name: mysql
          script: mysqldump.sh
          vars:
            mysql_user: backup
            mysql_password: backup
            mysql_endpoint: localhost
            mysql_databases:
              - site
            mysqldump_options: "--get-server-public-key"
          cron:
            hour: "*/6"
            minute: 30
        - name: s3_bucket
          script: s3_bucket.sh
          vars:
            bucket_name: photos
            s3_sync_path: "/mnt/photos-s3-mirror"
            s3_sync_options: "--follow-symlinks"
          cron:
            hour: 5
            minute: 20
            weekday: 0
        - name: mongodb
          script: mongodump.sh
          vars:
            mongodb_user: backup
            mongodb_password: backup
            mongodb_endpoint: localhost
          cron:
            hour: 7
            minute: 45
        - name: xtrabackup
          script: xtrabackup.sh
          vars:
            mysql_user: backup
            mysql_password: backup
            xtrabackup_backup_options: --slave-info
            xtrabackup_prepare_options: --use-memory=1G
        - name: docker_mariabackup
          script: docker_mariabackup.sh
          vars:
            mysql_container_name: project_mysql_1
            mysql_network_name: project_backend
            mysql_host: mysql
            mysql_user: backup
            mysql_password: backup
            mariabackup_docker_image: mariadb:latest
            mariabackup_options: --no-lock
          cron:
            hour: "*/1"
            minute: 27
        - name: influxdb
          script: influxdb.sh
          vars:
            influxdb_host: localhost:8086
            influxdb_token: influxdb-root-token-created-at-setup
          cron:
            hour: 21
            minute: 6
